src/filmd/gallery/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('filmd.gallery.views',
    url(r'^gallery/(?P<slug>[^\.]+)/$', 'gallery', name='gallery'),
    url(r'^gallereis/$', 'gallereis', name='gallereis'),
)

src/filmd/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',

    # url(r'^$', 'filmd.homepage.views.home', name='home'),

    (r'^$', direct_to_template, {
        'template': 'index.html'
    }),
    
    (r'^', include('filmd.gallery.urls')),
    (r'^', include('filmd.blog.urls')),
    (r'^', include('filmd.pages.urls')),

    (r'^comments/', include('django.contrib.comments.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

src/filmd/gallery/models.py
# -*- coding: utf-8 -*-
from django.db import models
import os.path
from django.contrib.sites.models import Site
from sorl.thumbnail import ImageField

class Gallery(models.Model):
        title = models.CharField(max_length=500, help_text="Заголовок")
        slug = models.SlugField(unique=True, help_text="ссылка")

        def get_absolute_url(self):
                return 'http://%s/gallery/%s/' % (Site.objects.get_current().domain, self.slug)

        def __unicode__(self):
                return self.title

        class Meta:
                verbose_name_plural = "Галерея"

class GalleryImage(models.Model):
    image = ImageField("Картинка", upload_to='gallery/images', help_text="Каритинка, .jpg, .png")
    title = models.CharField("Нащвание картинки", max_length=500, help_text="Заголовок", blank=True)

    gallery = models.ForeignKey('Gallery', help_text="Галерея")

    def get_title(self):
        return self.title if self.title else u'No name'

    class Meta:
        verbose_name_plural = "Картинки"

src/filmd/gallery/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from endless_pagination.decorators import page_template
from filmd.gallery.models import Gallery, GalleryImage

@page_template("archive_image.html")
def gallery(request, slug, template="gallery.html", extra_context=None):
    gallery = get_object_or_404(Gallery, slug=slug)
    context = {
        # 'url_prefix' : u'Галерея',
        # 'gallery': GalleryImage.objects.all(),
        'gallery' : gallery,
        'photos' : GalleryImage.objects.filter(gallery=gallery)
    }
    if extra_context is not None:
        context.update(extra_context)
    return render_to_response(template, context, context_instance=RequestContext(request))

def gallereis(request):
    template = "gallereis.html"
    context = {
        'gallery': Gallery.objects.all(),
    }
    return render(request, template, context)

src/filmd/gallery/templates/gallereis.html
{% extends "base.html" %}{% load thumbnail markup %}

{% block content %}
<div class="block no_bg">
    <div class="gallereis">{% for item in gallery %}
        <h3 class="title">{{ item.title }}</h3>
            {% for photo in item.galleryimage_set.all|slice:"1" %}
                    <a href="{{ photo.gallery.get_absolute_url }}">
                    {% thumbnail photo.image "400x300" crop="left" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                    </a>
            {% endfor %}
        {% endfor %}
    </div>
</div>

{% endblock %}

src/filmd/gallery/templates/gallery.html
{% extends "base.html" %}{% load thumbnail markup %}

{% block js %}
<link rel="stylesheet" type="text/css" href="/static/css/jquery.lightbox-0.5.css" media="screen" />
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/jquery.lightbox-0.5.js"></script>
<script language="JavaScript" type="text/javascript" src="/static/js/slides.jquery.js"></script>
{% endblock %}

{% block content %}
<div class="block no_bg">
    <h3>{{ gallery.title }}</h3>
    {% include page_template %}
</div>
{% endblock %}